### ISSUE TITLE
LineItemImport.project_ids name doesn't agree with type

### ISSUE THREAD

**Issue by rzuris** [bradbase/python-harvest_apiv2#17]
```
@dataclass
class LineItemImport:
    time: Optional[TimeImport]
    expenses: Optional[ExpenseImport]
    project_ids: List[Project]
```

I think that either `project_ids` should be renamed `projects` or else its data type should be changed to `List[int]`

**Comment by rzuris** [comment]
Actually, I get an error trying to create a LineItemImport even if I pass a Project (from create_project), because there are two different versions of `class Project` in harvestdataclasses.py, one that represents the return value from create_project and a different one that apparently is expected by LineItemImport.

**Comment by bradbase** [comment]
Hi @rzuris 

Thank you for reporting the bug.

You are correct, there are two dataclasses named "Project" which is no good at all.

Are you interested in offering a PR to fix it or are you looking for someone else to help with that?

**Comment by rzuris** [comment]
I suppose that I could take a stab at fixing it.

**Comment by bradbase** [comment]
You've already done most of the work :smiley:

Determining there are two different dataclasses called Project is the most difficult step.

Having two different classes of the same name is really embarrassing. Due to the way I wrote the library, and timelines in the moment, there is a real risk of the example you've found not being the only occurrence. Initially I only had a week or so to develop the library and I wrote it by going from endpoint to endpoint essentially ignoring context as I progressed. There have been quite a few really, really embarrassing things I've done in this library but, thankfully, they have been easy to fix. And I've tried to be responsive to publish fixes quickly.

I don't know what level of coding you're at but this project is fundamentally simple (once you get a hang of abstracted URL and HTTP header generation) -- so is great for beginners and not too taxing on experienced programmers.

I'm happy to offer assistance wherever you want it, if at all.

**Comment by rzuris** [comment]
Thanks for the assistance and encouragement. I think that I've got the corrections made. I renamed the first `Project` to `ProjectRef` and then fixed up references to it below that point (which you'll see in my changes easily enough). I am now testing the new version with my code. 

I incremented the version number in `metadata.py` from 1.9.0 to 1.9.1, but I see that the version that I already had installed was 1.10.0. Is it possible that you incremented the version number locally but never checked it in? In any case, I'll change the version in my copy to 1.10.1.

All of the tests pass, though I didn't write any new tests. That would take a fair amount of time, because there are a lot of layers of nested objects to create. Let me know if you want me to try to construct a test anyway.

**Comment by bradbase** [comment]
@rzuris Awesome!

version number.. damn I thought I'd kept that up-to-date. The only change in recent versions is the project name in setup.py. I was trying to change a hyphen to an underscore.

If you don't mind please increment version number to 1.11

I would like to arrange testing. That said I understand the potential complexity in setting that up. I only have a trial version of Harvest (eg; nothing terribly complex). If I can get guidance on the scenario which helped you discover the bug I might be able to spend the time in crafting a test.

Thanks so much.

**Comment by bradbase** [comment]
Hi @rzuris 

A friendly check-in...

How are you going with squashing this bug / is there anything you want a hand with?

**Comment by rzuris** [comment]
I created an integration test (using trial version of Harvest) that led me to discover the bug, so I will share that test to move the discussion along. My integration test is invoking an actual Harvest trial account rather than mocking (using a personal access token, using your test config INI format for the settings), so my test has to create all the dependent objects for an invoice, and then delete everything it creates. It initializes minimum fields in each type of object, rather than initializing every field like your tests do.

[test_integration.zip](https://github.com/bradbase/python-harvest_apiv2/files/5547140/test_integration.zip)

I'll push my changes to my fork in a little bit.

**Comment by rzuris** [comment]
Slight update to integration test to account for type hint added to `create_invoice_based_on_tracked_time_and_expenses`.
[test_integration.zip](https://github.com/bradbase/python-harvest_apiv2/files/5547895/test_integration.zip)

**Comment by rzuris** [comment]
Hi Brad, let me know what the next step is. I'm not sure what to do about the test-coverage complaint in the PR. And I'm not sure what to do about testing the changes that I submitted beyond sharing my integration test, which exercises the APIs in question.

**Comment by bradbase** [comment]
@rzuris This is great.

The test coverage thing is a very high bar as code projects go. That said, I have found it is absolutely fantastic for stopping a project from going backwards. I have a feeling the coveralls doesn't care if the added code is specifically tested, just that test coverage keeps up as a percentage.

I'll take a look at the contribution now and see if we can get it across the line.

**Comment by bradbase** [comment]
OK... the code coveralls wants to see exercised are in methods;
- create_free_form_invoice
- create_invoice_based_on_tracked_time_and_expenses

Neither of which are currently exercised in the unit tests.

create_invoice_based_on_tracked_time_and_expenses is in your integration test script.

Your test script is using Harvest to assemble the data structures we need for the unit testing. For the unit testing we need to somehow capture those object hierarchies and re-create them by hand. It's a pain but isn't (usually) horrendous.

The project_ref vs project object, however, is a different thing to test.

**Comment by bradbase** [comment]
So many moving parts spread so far... You've done very well to get this far.

I'll make a coffee then craft up some tests to test the object hierarchies.

**Comment by rzuris** [comment]
I could capture the objects that the integration test creates and save the json to use in the unit tests, if that helps

**Comment by bradbase** [comment]
One puzzle...

The tests work whether using your (quite rightly) updated dataclasses or not.

**Comment by bradbase** [comment]
Figured it. ID10T error. Too much water under the bridge. The unit tests can't replicate what Harvest are actually doing so the staged response is what you get back from calling a method. The entire point of using httpretty but makes the tests not really "do" all that much.

I'm back on track now.

The official Harvest API doesn't have an endpoint called Create Invoice. Each of create_free_form_invoice() and create_invoice_based_on_tracked_time_and_expenses() call create_invoice().

When we look at the example request provided by Harvest for each of [Create Free Form Invoice](https://help.getharvest.com/api-v2/invoices-api/invoices/invoices/#create-a-free-form-invoice) and [Create Invoice Based on Tracked Time and Expenses](https://help.getharvest.com/api-v2/invoices-api/invoices/invoices/#create-an-invoice-based-on-tracked-time-and-expenses) we can see the only difference between them is the detail of the invoice being POSTed so I have channeled them through one method to construct the POST request.

Each of our two methods need to be a wrapper for create_invoice().

Some background.. Whether it was a good decision or not the class Harvest mostly "passes around" (/modifies) kwargs as the structure of choice rather than passing around purpose-built objects (eg; instances of dataclasses) or a separately managed dict. I can accept this might be a little crap and is obscure as it falls outside most commonly used paradigms. My consideration on this; The class Harvest is simply trying to assemble a web request by applying operations "to" the request until it eventually gets sent -- albeit with a small amount of management surrounding OAuth and request limits. Most calls are simple and method arguments work just fine. The only complex calls are the "create" ones where you do actually need to hand over a complex object. I have assumed a Python dict is the common denominator and so that is the conduit for the call. The interface for return values is objectified because the users of the client are likely to be object-oriented.

This begs the questions:
- Must we insist that the dataclasses are used to initiate a request?
- Is there a need to support both? (eg; test for dataclass instance and asdict on behalf of the user if we find a dataclass instance)

Any particular opinion on these questions @ptitiano?
