### ISSUE TITLE
Avoid GET requests with contents in the body

### ISSUE THREAD

**Issue by mrsimo** [bradbase/python-harvest_apiv2#22]
Hi @bradbase! I'm writing on behalf of the Harvest team, I'm with the SRE team here 👋🏻. 

We are going to be making some changes on August 15th that will likely break this library. We've found some activity in our logs with the `bradbase/python-harvest-apiv2` user agent (thank you so much for providing a proper User Agent 🙏🏻) that detects contents in the body of GET requests. We're going to make some changes that will cause these requests to start failing and return 400's, so we'd appreciate it if this could be fixed and a new version released, so we can tell the customers that are relying on this package.

From what I can see, these GET requests contain the string `null` in the body (as in the four characters forming the word "null"). I'm not very familiar with Python, unfortunately, but I think it might have to do with [these lines](https://github.com/bradbase/python-harvest_apiv2/blob/8faa4fd6b163b61983c4ebedbd7eba133b466b2c/harvest/harvest.py#L1006-L1007) where `data` is always set to whatever `json.dumps(data)` returns. I imagine if `data` is null, then that might return the string `null`?

Thanks a lot for working on this library 🎉! And let me know if I can be of any help with this!

**Comment by bradbase** [comment]
Hi @mrsimo,

Thank you for bringing this to my attention. I am coming up with an approach to resolve this.

Is it possible to get access to a preview interface to test against?

Will the Harvest API still be called version 2?

**Comment by minac** [comment]
👋  @bradbase, my name is Miguel and I'm helping out @mrsimo with this issue here at Harvest.

**A bit of context**
We are not making changes to the API itself. 
We are moving our infrastructure over to a different provider which doesn't accept HTTP requests outside of the HTTP standards.

**Time crunch**
We are, unfortunately, short on time as the change will happen on the 15th of August, so if you could come up with a fix in the next couple of days it would be great! We would then also alert anyone that we can see using the integration from our side so they can upgrade to the new version asap.

**Testing**
There is no new version of the API, but I'm happy to work with you (real-time if you want) to tell you how the requests are coming in by looking at our logs.

Thanks again for being open to this, and I look forward to your update.

**Comment by bradbase** [comment]
Within the last 5 minutes I have done a few GET requests to get company using user-agent bradbase/python-harvest-apiv2_v1.12.0

**Comment by minac** [comment]
Apologies, I was in meetings. 
I'm happy to report that it looks 👍! The requests you sent with the new user agent all passed with flying colors.

**Comment by bradbase** [comment]
@minac No worries. work isn't about the fun stuff 😃 

That's great news. Sounds like we have a release candidate.

**Comment by bradbase** [comment]
@minac Is is possible to have the Harvest integrations directory to change the Python-Harvest entry?

So, the " Learn More" button from this page:
https://www.getharvest.com/integrations/python-library

I'd like to move it from the GitHub repo to a squarespace website;
https://dachshund-turbot-6p52.squarespace.com/

**Comment by minac** [comment]
Hey @bradbase. The link has been updated!

**Comment by bradbase** [comment]
@minac That's fantastic news. Thank you.

I am starting to feel we are getting to the end of this pre-emptive bugfix journey. Or, at least, as much as I can do.

I would very much like to contact our users in advance but I have absolutely no ability to determine who they are.

Is there a newsletter or something published by Harvest that I could write an article for, or we (/Harvest?) could somehow broadcast this change? eg; a broadcast where I don't get access to the Harvest client list, but we can highlight taking on this change...

**Comment by minac** [comment]
I'm afraid that we do not have a newsletter for this type of thing, but I'm confident people can read this issue and get up to date. What are the steps for the users of this integration to get to the new version?

**Comment by bradbase** [comment]
I guess I should write an issue for that. In the mean-time...

Version 1.12.0 has only 2 changes from 1.11.0 so I would expect it to be a fairly easy drop-in replacement/upgrade;
- GET parameters “from_date”, “to_date” renamed to “from”, “to”. Issue #21
- Ensure GET requests have no body. Issue #22 (Breaking change from Harvest)
- include tests for the above

The path of least resistance is buy a copy of 1.12.0 from the squarespace site I have set up and pip install from the downloaded .zip archive. If you just need a copy with the non-breaking change;
https://dachshund-turbot-6p52.squarespace.com/order/p/python-harvest-library-v1110

The above URL looks wrong but it's because I have swapped out v1.11.0 for 1.12.0 in the download link - this is my first squarespace site so I'm still getting used to it.

Otherwise, there are other ways in;
https://dachshund-turbot-6p52.squarespace.com/deals

For future reference I have a changelog on the website:
https://dachshund-turbot-6p52.squarespace.com/changelog

And I have a ToDo list:
https://dachshund-turbot-6p52.squarespace.com/todo

Currently I'm working on writing documentation for the library. In particular, providing a list of all the supported methods and very clear copy+paste style examples of how to use each method. It's going to take a few more days to get the first-cut doco up-to-scratch. Maybe even the end of the week. I don't yet have it published on the net but a link to the doco will be put up on the squarespace website.

In terms of what's coming...

1.13.0 already has the below and I will release it when the example style documentation is finished.
- Support weekly_capacity on Company
- Support Company update
- Support HTTP 400
- Cleaned up some of the tests
- Improved documentation for at least
    - Company
    - Roles
    - Clients
    - Client Contacts
    - Invoice Messages
    - Invoices

**Comment by bradbase** [comment]
An example of the documentation being written.

![Python-Harvest_delete_invoice_payment](https://user-images.githubusercontent.com/47906258/128715937-45b95408-a1cc-4c71-adc2-99b7e741abe5.PNG)

**Comment by bradbase** [comment]
@minac I hope the system migration went well.

Are you seeing any residual use of v1.12.0?

Cheers

**Comment by karunkrishna** [comment]
Hi guys, I'm currently using v 1.11.0; and this package no longer works. 
Any Idea when v 1.12.0 will be publicly available?

**Comment by bradbase** [comment]
Hi @karunkrishna 

The model for Python-Harvest has changed.

I had found myself in a situation where businesses were asking for bug fixes and feature changes, on a timeline that suits them, but not offering up code through a PR or payment. This is not the culture I had expected by going open source and so I have made a change.

Python-Harvest is now available for purchase. It is currently at v1.13.0 and is accompanied by documentation, changelog and todo list.

It is available at the squarespace shopfront here:
https://dachshund-turbot-6p52.squarespace.com

Cheers,

Brad

**Comment by minac** [comment]
> @minac I hope the system migration went well.

Hi @bradbase! Thanks for asking. On the 17th we did a 24h brownout and decided to give people one more week to update their code. Tomorrow (the 24th) we'll be making the change persistent for everyone.

> Are you seeing any residual use of v1.12.0?

We are, but that version will not work from tomorrow.

Thanks for checking in.

**Comment by bradbase** [comment]
@minac Thank you and the Harvest team.

This explains a lot :D

The brownout has yielded two inquiries about the HTTP 400s. I suspect that since you've undone the change, and I am charging for the later release, those two people are likely to have continued with the legacy version.

Due to not having a comprehensive contact list there is no real way for me to proactively reach the users of this library.

With respect to the library I am a sole trader with no employees or contractors and am employed full-time for a company doing non-Python-Harvest things. That means a hard-cut over with a great number of people to support may result in delayed or inadequate support. Without knowing how many people and companies are using this library there is no way to prepare myself for the consequences of a hard cut-over.

I accept that Harvest are unlikely to be interested in initiating communications surrounding a product that isn't theirs. That said, as far as I can tell the logs of which users are using this library and their contact details are on your end so the only people empowered to do a proactive communication are Harvest.

I understand if the delay in cementing your change considers other libraries and products, but the only way I can find who is using my library is if Harvest makes the breaking change and the users reach out to complain.

Thank you for letting me know it will switch over permanently tomorrow.

**Comment by bradbase** [comment]
@minac Thank you and the Harvest team.

It appears the switch over to your new environment has been completed.

Are you satisfied we have sufficiently addressed the impending HTTP 400 errors got GET requests?

Cheers,

Brad

**Comment by minac** [comment]
Hi @bradbase! Yes, we are down to a residual amount of requests from this integration that are still using the old version. Please feel free to close this issue.

Kind regards,
Miguel

**Comment by bradbase** [comment]
Thank you.
